export const ERROR_MESSAGE = {
  AUTH: {
    LOGIN: "Could not login",
    REGISTER: "Could not register",
    VERIFY: "Could not verify",
    REFRESH: "Could not refresh token",
  },
  USER: {
    RETRIEVE: "Could not retrieve users",
    RETRIEVE_BY_ID: "Could not retrieve user",
    RETRIEVE_BY_EMAIL: "Could not retrieve user by email",
    RETRIEVE_BY_USERNAME: "Could not retrieve user by username",
    CREATE: "Could not create user",
    UPDATE: "Could not update user",
    DELETE: "Could not delete user",
    RETRIEVE_CHATS: "Could not retrieve user chats",
    RETRIEVE_MESSAGES: "Could not retrieve chat messages",
    STATUS: "Could not set user status",
    VERIFY: "Could not verify user",
    RETRIEVE_BY_REFRESH_TOKEN: "Could not retrieve user by refresh token",
    RETRIEVE_CONTACTS: "Could not retrieve user contacts",
    LOGOUT: "Could not logout user",
  },
  CHAT: {
    RETRIEVE: "Could not retrieve chats",
    RETRIEVE_BY_ID: "Could not retrieve chat",
    RETRIEVE_BY_USER_ID: "Could not retrieve chats by user id",
    RETRIEVE_MESSAGES_BY_ID: "Could not retrieve chat messages by id",
    RETRIEVE_BY_IDS: "Could not retrieve chats by ids",
    CREATE: "Could not create chat",
    UPDATE: "Could not update chat",
    DELETE: "Could not delete chat",
    UPDATE_UNREAD_COUNT: "Could not update unread count",
  },
  MESSAGE: {
    RETRIEVE: "Could not retrieve messages",
    CREATE: "Could not create message",
    UPLOAD_FILE: "Could not upload file",
    UPDATE: "Could not update message",
  },
  ATTACHMENT: {
    RETRIEVE: "Could not retrieve attachments",
  },
  TRANSACTION: {
    RETRIEVE: "Could not retrieve transactions",
    ADD_WALLET: "Could not add wallet",
    DELETE_WAALLET: "Could not delete wallet",
    CREATE: "Could not create transaction",
  }
};
